pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build
         --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
         --label build-number=$DRONE_BUILD_NUMBER
         --label build-date="$(date)"
         -t swarnaarukha/example-webserver:$DRONE_COMMIT_SHA .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run swarnaarukha/example-webserver:$DRONE_COMMIT_SHA /test.sh

  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u swarnaarukha -p $PASS
      - docker push swarnaarukha/example-webserver:$DRONE_COMMIT_SHA

  deploy:
   image: docker
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   commands:
     - docker pull swarnaarukha/example-webserver:$DRONE_COMMIT_SHA
     - docker tag swarnaarukha/example-webserver:$DRONE_COMMIT_SHA
              swarnaarukha/example-webserver:latest
     - docker stack deploy -c ./docker-compose.yml example-webserver
